/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panel.MainPanel;

import PhysixLib.MathUtils;
import UI.Panel.InforPanel.SideCalInformation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author thanhtr
 */
public class SideCalculation extends javax.swing.JPanel {

    /**
     * Creates new form SideCalculation
     */
    public SideCalculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        txtAngle = new javax.swing.JTextField();
        lblAngle = new javax.swing.JLabel();
        lblHypotenuse = new javax.swing.JLabel();
        lblAdjacent = new javax.swing.JLabel();
        lblOpposite = new javax.swing.JLabel();
        lblOppositeAns = new javax.swing.JLabel();
        lblAdjacentAns = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lblm2 = new javax.swing.JLabel();
        lblm3 = new javax.swing.JLabel();
        txtHypotenuse = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        btnDegreeRad = new javax.swing.JButton();
        lblDegree = new javax.swing.JLabel();

        lblWelcome.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lblWelcome.setText("Welcome to PhysiX");

        lblCopyright.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lblCopyright.setText("Copyright IPEramus 2013");

        txtAngle.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtAngle.setText("    ");

        lblAngle.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblAngle.setText("Angle");

        lblHypotenuse.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblHypotenuse.setText("Hypotenuse");

        lblAdjacent.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblAdjacent.setText("Adjacent");

        lblOpposite.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblOpposite.setText("Opposite");

        lblOppositeAns.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblOppositeAns.setText("   ");

        lblAdjacentAns.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblAdjacentAns.setText("   ");

        lblm.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblm.setText("m");

        lblm2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblm2.setText("m");

        lblm3.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblm3.setText("m");

        txtHypotenuse.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnInfo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnInfo.setText("Information");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnCal.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        btnDegreeRad.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnDegreeRad.setText("Degree/Radian");
        btnDegreeRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegreeRadActionPerformed(evt);
            }
        });

        lblDegree.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblDegree.setText("Degree");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCopyright))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAngle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHypotenuse)
                                    .addComponent(lblAdjacent)
                                    .addComponent(lblOpposite))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblOppositeAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAdjacentAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHypotenuse)
                                    .addComponent(txtAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDegree)
                                    .addComponent(lblm2)
                                    .addComponent(lblm3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDegreeRad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblm)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblCopyright))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAngle)
                    .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDegreeRad)
                    .addComponent(lblDegree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHypotenuse)
                    .addComponent(lblm)
                    .addComponent(txtHypotenuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdjacentAns)
                    .addComponent(lblAdjacent)
                    .addComponent(lblm2)
                    .addComponent(btnCal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpposite)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblm3)
                        .addComponent(lblOppositeAns)
                        .addComponent(btnInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        try {
            float ang = Float.parseFloat(txtAngle.getText());
            if (lblDegree.getText().equalsIgnoreCase("Degree")) {
                ang = MathUtils.Deg2Rad(ang);
            }
            float h = Float.parseFloat(txtHypotenuse.getText());
            if (h<=0) throw new ArithmeticException();
            lblAdjacentAns.setText(Float.toString(MathUtils.AdjacentSide(ang, h)));
            lblOppositeAns.setText(Float.toString(MathUtils.OppositeSide(ang, h)));
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(this, 
                    "Hypotenuse must be higher than zero.\n"
                    + "Please enter the hypotenuse again");
            lblAdjacentAns.setText("");
            lblOppositeAns.setText("");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, 
                    "Please enter hypotenuse and angle in the right form");
            lblAdjacentAns.setText("");
            lblOppositeAns.setText("");
        }
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnDegreeRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegreeRadActionPerformed
        // TODO add your handling code here:
        if (txtAngle.getText().trim().length() > 0) {
            try {
                if (lblDegree.getText().equalsIgnoreCase("Degree")) {
                    lblDegree.setText("Radian");
                    txtAngle.setText(
                            Float.toString(
                            MathUtils.Deg2Rad(Float.parseFloat(txtAngle.getText()))));
                } else {
                    lblDegree.setText("Degree");
                    txtAngle.setText(
                            Float.toString(
                            MathUtils.Rag2Deg(Float.parseFloat(txtAngle.getText()))));

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter the angle in the right form");
                lblAdjacentAns.setText("");
                lblOppositeAns.setText("");
            }
        } else {
            if (lblDegree.getText().equalsIgnoreCase("Degree")) {
                lblDegree.setText("Radian");
            } else {
                lblDegree.setText("Degree");
            }
        }

    }//GEN-LAST:event_btnDegreeRadActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        JFrame infoFr = new JFrame();
        infoFr.setContentPane(new SideCalInformation());
        infoFr.pack();
        infoFr.setVisible(true);
        infoFr.setTitle("About calculating side");
        infoFr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnInfoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnDegreeRad;
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel lblAdjacent;
    private javax.swing.JLabel lblAdjacentAns;
    private javax.swing.JLabel lblAngle;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblDegree;
    private javax.swing.JLabel lblHypotenuse;
    private javax.swing.JLabel lblOpposite;
    private javax.swing.JLabel lblOppositeAns;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lblm2;
    private javax.swing.JLabel lblm3;
    private javax.swing.JTextField txtAngle;
    private javax.swing.JTextField txtHypotenuse;
    // End of variables declaration//GEN-END:variables
}
