/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panel.MainPanel;

import PhysixLib.MathUtils;
import UI.Panel.InforPanel.VectorAngleInformation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author thanhtr
 */
public class VectorAngle extends javax.swing.JPanel {

    /**
     * Creates new form VectorAngle
     */
    public VectorAngle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVector2 = new javax.swing.JLabel();
        txtI2 = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        lblCopyright = new javax.swing.JLabel();
        lblVector1 = new javax.swing.JLabel();
        txtI1 = new javax.swing.JTextField();
        lblI1 = new javax.swing.JLabel();
        txtJ1 = new javax.swing.JTextField();
        lblJ1 = new javax.swing.JLabel();
        txtK1 = new javax.swing.JTextField();
        lblK1 = new javax.swing.JLabel();
        lblAngleAns = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblK2 = new javax.swing.JLabel();
        txtK2 = new javax.swing.JTextField();
        lblJ2 = new javax.swing.JLabel();
        txtJ2 = new javax.swing.JTextField();
        lblI2 = new javax.swing.JLabel();
        lblToggleRadDeg = new javax.swing.JLabel();
        btnToggleRadDeg = new javax.swing.JButton();

        lblVector2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVector2.setText("Vector 2");

        txtI2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtI2.setText("  ");

        btnInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInfo.setText("Information");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnCal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        lblCopyright.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCopyright.setText("Copyright by IPEramus 2013");

        lblVector1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVector1.setText("Vector 1");

        txtI1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtI1.setText("  ");

        lblI1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblI1.setText(" i + ");

        txtJ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJ1.setText("  ");

        lblJ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJ1.setText(" j + ");

        txtK1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtK1.setText("  ");

        lblK1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblK1.setText(" k");

        lblAngleAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAngleAns.setText("   ");

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWelcome.setText("Welcome to PhysiX");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Angle");

        lblK2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblK2.setText(" k");

        txtK2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtK2.setText("  ");

        lblJ2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJ2.setText(" j + ");

        txtJ2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJ2.setText("  ");

        lblI2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblI2.setText(" i + ");

        lblToggleRadDeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblToggleRadDeg.setText("Degree");

        btnToggleRadDeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnToggleRadDeg.setText("Deg/Rad");
        btnToggleRadDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleRadDegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCopyright))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVector2)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtI2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblI2))
                                    .addComponent(lblAngleAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblJ2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblK2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblToggleRadDeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnToggleRadDeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVector1)
                                .addGap(18, 18, 18)
                                .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblI1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJ1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblK1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInfo)
                            .addComponent(btnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblCopyright))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVector1)
                            .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblI1)
                            .addComponent(txtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJ1)
                            .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblK1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVector2)
                            .addComponent(txtI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblI2)
                            .addComponent(txtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJ2)
                            .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblK2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblAngleAns)
                            .addComponent(lblToggleRadDeg)
                            .addComponent(btnToggleRadDeg)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        try {
            float z1, z2;
            if (txtK1.getText().trim().length() == 0) {
                z1 = 0;
                txtK1.setText("0");
            } else {
                z1 = Float.parseFloat(txtK1.getText());
            }
            if (txtK2.getText().trim().length() == 0) {
                z2 = 0;
                txtK2.setText("0");
            } else {
                z2 = Float.parseFloat(txtK2.getText());
            }
            PhysixLib.Vector v1 = new PhysixLib.Vector(
                    Float.parseFloat(txtI1.getText()),
                    Float.parseFloat(txtJ1.getText()),
                    z1);
            PhysixLib.Vector v2 = new PhysixLib.Vector(
                    Float.parseFloat(txtI2.getText()),
                    Float.parseFloat(txtJ2.getText()),
                    z2);
            float ang = v1.AngleVec(v2);
            if (lblToggleRadDeg.getText().equalsIgnoreCase("Degree")) {
                ang = MathUtils.Rag2Deg(ang);
            }
            lblAngleAns.setText(Float.toString(ang));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter two vectors in the right form");
            lblAngleAns.setText("");
        }
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnToggleRadDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleRadDegActionPerformed
        // TODO add your handling code here:
        if (lblAngleAns.getText().trim().length() == 0) {
            if (lblToggleRadDeg.getText().equalsIgnoreCase("Degree")) {
                lblToggleRadDeg.setText("Radian");
            } else {
                lblToggleRadDeg.setText("Degree");
            }
        } else {
            if (lblToggleRadDeg.getText().equalsIgnoreCase("Degree")) {
                lblToggleRadDeg.setText("Radian");
                lblAngleAns.setText(Float.toString(
                        MathUtils.Deg2Rad(Float.parseFloat(lblAngleAns.getText()))));
            } else {
                lblToggleRadDeg.setText("Degree");
                lblAngleAns.setText(Float.toString(
                        MathUtils.Rag2Deg(Float.parseFloat(lblAngleAns.getText()))));
            }
        }
    }//GEN-LAST:event_btnToggleRadDegActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        JFrame infoFr = new JFrame();
        infoFr.setContentPane(new VectorAngleInformation());
        infoFr.pack();
        infoFr.setVisible(true);
        infoFr.setTitle("About Angle between 2 Vectors");
        infoFr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnInfoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnToggleRadDeg;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblAngleAns;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblI1;
    private javax.swing.JLabel lblI2;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblK1;
    private javax.swing.JLabel lblK2;
    private javax.swing.JLabel lblToggleRadDeg;
    private javax.swing.JLabel lblVector1;
    private javax.swing.JLabel lblVector2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtI1;
    private javax.swing.JTextField txtI2;
    private javax.swing.JTextField txtJ1;
    private javax.swing.JTextField txtJ2;
    private javax.swing.JTextField txtK1;
    private javax.swing.JTextField txtK2;
    // End of variables declaration//GEN-END:variables
}
