/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panel.MainPanel;

import UI.Panel.InforPanel.VectorDotPInformation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author thanhtr
 */
public class VectorDotProduct extends javax.swing.JPanel {

    /**
     * Creates new form VectorDotProduct
     */
    public VectorDotProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDotAns = new javax.swing.JLabel();
        lblK1 = new javax.swing.JLabel();
        txtK1 = new javax.swing.JTextField();
        lblVector1 = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        txtJ1 = new javax.swing.JTextField();
        lblI1 = new javax.swing.JLabel();
        txtI1 = new javax.swing.JTextField();
        lblK2 = new javax.swing.JLabel();
        txtK2 = new javax.swing.JTextField();
        lblDotProduct = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblI2 = new javax.swing.JLabel();
        lblJ2 = new javax.swing.JLabel();
        txtJ2 = new javax.swing.JTextField();
        lblVector2 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        txtI2 = new javax.swing.JTextField();
        lblCopyright = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();

        lblDotAns.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblDotAns.setText("  ");

        lblK1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblK1.setText(" k");

        txtK1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtK1.setText("  ");

        lblVector1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblVector1.setText("Vector 1");

        lblJ1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblJ1.setText(" j + ");

        txtJ1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtJ1.setText("  ");

        lblI1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblI1.setText(" i + ");

        txtI1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtI1.setText("  ");

        lblK2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblK2.setText(" k");

        txtK2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtK2.setText("  ");

        lblDotProduct.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblDotProduct.setText("Dot Product");

        lblWelcome.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lblWelcome.setText("Welcome to PhysiX");

        lblI2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblI2.setText(" i + ");

        lblJ2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblJ2.setText(" j + ");

        txtJ2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtJ2.setText("  ");

        lblVector2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblVector2.setText("Vector 2");

        btnInfo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnInfo.setText("Information");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        txtI2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txtI2.setText("  ");

        lblCopyright.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        lblCopyright.setText("Copyright by IPEramus 2013");

        btnCal.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCopyright)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDotProduct)
                                .addGap(31, 31, 31)
                                .addComponent(lblDotAns, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVector1)
                                    .addComponent(lblVector2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblI1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblJ1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblK1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtI2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblI2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblJ2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblK2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInfo)))))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblCopyright))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVector1)
                    .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblI1)
                    .addComponent(txtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJ1)
                    .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblK1)
                    .addComponent(btnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVector2)
                    .addComponent(txtI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblI2)
                    .addComponent(txtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJ2)
                    .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblK2)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDotProduct)
                    .addComponent(lblDotAns))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        try {
            float z1, z2;
            if (txtK1.getText().trim().length() == 0) {
                z1 = 0;
                txtK1.setText("0");
            } else {
                z1 = Float.parseFloat(txtK1.getText());
            }
            if (txtK2.getText().trim().length() == 0) {
                z2 = 0;
                txtK2.setText("0");
            } else {
                z2 = Float.parseFloat(txtK2.getText());
            }
            PhysixLib.Vector v1 = new PhysixLib.Vector(
                    Float.parseFloat(txtI1.getText()),
                    Float.parseFloat(txtJ1.getText()),
                    z1);
            PhysixLib.Vector v2 = new PhysixLib.Vector(
                    Float.parseFloat(txtI2.getText()),
                    Float.parseFloat(txtJ2.getText()),
                    z2);

            lblDotAns.setText(Float.toString(v1.DotProduct(v2)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter two vectors in the right form");
            lblDotAns.setText("");
        }
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        JFrame infoFr = new JFrame();
        infoFr.setContentPane(new VectorDotPInformation());
        infoFr.pack();
        infoFr.setVisible(true);
        infoFr.setTitle("About calculating the Dot product between 2 Vectors");
        infoFr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnInfoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblDotAns;
    private javax.swing.JLabel lblDotProduct;
    private javax.swing.JLabel lblI1;
    private javax.swing.JLabel lblI2;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblK1;
    private javax.swing.JLabel lblK2;
    private javax.swing.JLabel lblVector1;
    private javax.swing.JLabel lblVector2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtI1;
    private javax.swing.JTextField txtI2;
    private javax.swing.JTextField txtJ1;
    private javax.swing.JTextField txtJ2;
    private javax.swing.JTextField txtK1;
    private javax.swing.JTextField txtK2;
    // End of variables declaration//GEN-END:variables
}
